### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by ran-j** [mathquis/node-personal-wakeword#1]
Can you provide the audio samples that you  used ? 

```
// Add a new keyword using multiple "templates"
	await detector.addKeyword('alexa', [
		// WAV templates (trimmed with no noise!)
		'./keywords/alexa1.wav',
		'./keywords/alexa2.wav',
		'./keywords/alexa3.wav'
	], {
		// Options
		disableAveraging: true, // Disabled by default, disable templates averaging (note that resources consumption will increase)
		threshold: 0.52 // Per keyword threshold
	})
```

**Comment by mathquis** [comment]
As the audio templates only works for a specific voice (the one in the template) I do not think that providing mine will be of any use to anyone else.

You can easily record your own using tools like Audacity. As explained in the Snips documentation:
> In order for the model to perform well, the environment where you record your samples must be as quiet as possible so you must avoid place with background noise (music, tv, people speaking ...).

Hope this helps.
