### ISSUE TITLE
Question Mobile

### ISSUE THREAD

**Issue by silvioviscuso** [mathquis/node-personal-wakeword#5]
hi I would like to ask a trivial information, could I implement this library for a project in react native?  simply a personal assistant

**Comment by silvioviscuso** [comment]
to use it with react native can you use nodejs as a backend?

**Comment by mathquis** [comment]
This module uses my native Node.js port of a C++ audio library called Gist to calculate MFCC from audio frames so it will not work as is on mobile.

If your mobile app forward audio frames to a Node backend server then yes it can work. 

I am not familiar enough with React Native modules to make things work on Android or iOS but feel free to use any parts you need.
